rollout:
  enabled: true    

backend:
  replicaCount: 1
  image:
    repository: argoproj/rollouts-demo   # <— official demo image
    tag: yellow                            # blue|green|yellow|orange
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8080          # rollouts-demo listens on 8080
    targetPort: 8080
    nodePort: 30000
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi  

frontend:
  replicaCount: 1
  image:
    repository: nginx                    # lightweight static server
    tag: 1.25-alpine
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80            # nginx listens on 80
    targetPort: 80
    nodePort: 30001
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi