rollout:
  enabled: true    

backend:
  replicaCount: 1
  image:
    repository: argoproj/rollouts-demo   # <— official demo image
    tag: yellow                            # blue|green|yellow|orange
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8080          # rollouts-demo listens on 8080
    targetPort: 8080
    nodePort: 30000
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 32Mi