apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-app
  name: solar-app
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: solar-app
  template:
    metadata:
      labels:
        app: solar-app
    spec:
      containers:
      - image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        name: solar-app
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports: 
        - containerPort: {{ .Values.backend.service.targetPort }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 12 }}