{{- if .Values.rollout.enabled }} # Only create this resource if rollout is enabled in values
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: solar-app # Name of the Rollout resource
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels: { app: solar-app } # Labels to identify which pods to manage
  template: # Pod template for creating new pods
    metadata:
      labels:
        app: solar-app # Must match the selector's matchLabels
    spec:
      containers:
      - name: solar-app
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports: [{ containerPort: {{ .Values.backend.service.targetPort }} }]
        resources: {{- toYaml .Values.backend.resources | nindent 10 }}
  strategy:
    blueGreen:
      activeService:  solar-app-active
      previewService: solar-app-preview
      autoPromotionEnabled: false
      previewReplicaCount: {{ .Values.backend.replicaCount }}
{{- end }}