{{- if .Values.rollout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: solar-app-preview
spec:
  selector:
    app: solar-app
    rollout.argoproj.io/bluegreen: preview
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
{{- end }}