apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solar-app-of-apps
spec:
  destination:
    name: gh-codespaces-demo
    namespace: argocd
  source:
    path: solar-app/apps
    repoURL: https://github.com/himeshpanc/m5-tutorial.git
    targetRevision: gh
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true