apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solar-qa
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  source:
    path: solar-app/charts/solar
    repoURL: https://github.com/himeshpanc/m5-tutorial.git
    targetRevision: gh
    helm:
      valueFiles:
      - values-qa.yaml
  project: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
