apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solar-dev
spec:
  destination:
    name: himesh-corp-mac
    namespace: dev
  source:
    path: solar-app/charts/solar
    repoURL: https://github.com/himeshpanc/m5-tutorial.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-dev.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  
    syncOptions:
      - CreateNamespace=true